import { PipelineConnector, CampaignData, AttributionModelType, AttributionChannelMetric, ExecutionRule, IntelligenceAlert, PipelineEventLog } from '@/types/xion';

export const INITIAL_PIPELINES: PipelineConnector[] = [
  {
    id: 'pipe-meta-ads',
    name: 'Meta Ads Realtime Stream',
    channel: 'meta',
    channelLabel: 'Meta Marketing API',
    status: 'active',
    eventsPerSec: 1420,
    totalEvents24h: 122680000,
    latencyMs: 38,
    errorRate: 0.002,
    lastSync: 'Just now',
    schemaFields: ['ad_id', 'adset_id', 'campaign_id', 'spend', 'impressions', 'cpc', 'cpa', 'reach'],
    protocol: 'REST Webhook',
  },
  {
    id: 'pipe-google-search',
    name: 'Google Ads Data Stream',
    channel: 'google',
    channelLabel: 'Google Ads API v17',
    status: 'active',
    eventsPerSec: 2180,
    totalEvents24h: 188400000,
    latencyMs: 24,
    errorRate: 0.001,
    lastSync: 'Just now',
    schemaFields: ['customer_id', 'ad_group_criterion', 'metrics.cost_micros', 'metrics.conversions_value', 'quality_score'],
    protocol: 'gRPC',
  },
  {
    id: 'pipe-tiktok-pixel',
    name: 'TikTok Events API Stream',
    channel: 'tiktok',
    channelLabel: 'TikTok Marketing API',
    status: 'active',
    eventsPerSec: 890,
    totalEvents24h: 76900000,
    latencyMs: 44,
    errorRate: 0.005,
    lastSync: '1s ago',
    schemaFields: ['event_id', 'pixel_code', 'advertiser_id', 'timestamp', 'conversion_event', 'video_play_actions'],
    protocol: 'REST Webhook',
  },
  {
    id: 'pipe-dsp-bidstream',
    name: 'The Trade Desk Bidstream & Win Logs',
    channel: 'programmatic',
    channelLabel: 'TTD Real-Time Event Bus',
    status: 'active',
    eventsPerSec: 4650,
    totalEvents24h: 401760000,
    latencyMs: 12,
    errorRate: 0.0004,
    lastSync: 'Just now',
    schemaFields: ['bid_request_id', 'deal_id', 'clearing_price', 'geo_dma', 'device_type', 'viewability_score'],
    protocol: 'Kafka',
  },
  {
    id: 'pipe-shopify-cdc',
    name: 'Commerce Conversion Ingestion',
    channel: 'shopify',
    channelLabel: 'Shopify Webhooks / Storefront',
    status: 'active',
    eventsPerSec: 320,
    totalEvents24h: 27640000,
    latencyMs: 19,
    errorRate: 0.0001,
    lastSync: 'Just now',
    schemaFields: ['order_id', 'cart_token', 'checkout_completed_at', 'total_price_usd', 'attribution_utm_source', 'customer_ltv'],
    protocol: 'Segment Spec',
  },
  {
    id: 'pipe-snowflake-sink',
    name: 'Snowflake Enterprise Warehouse Sink',
    channel: 'snowflake',
    channelLabel: 'Snowflake Snowpipe Streaming',
    status: 'active',
    eventsPerSec: 9460,
    totalEvents24h: 817380000,
    latencyMs: 65,
    errorRate: 0.0002,
    lastSync: 'Just now',
    schemaFields: ['event_uuid', 'session_hash', 'unified_identity_key', 'attribution_vector', 'ingestion_epoch'],
    protocol: 'Snowflake CDC',
  }
];

export const INITIAL_CAMPAIGNS: CampaignData[] = [
  {
    id: 'cmp-meta-scale-01',
    name: 'Global Advantage+ Prospecting Q3',
    channel: 'meta',
    channelLabel: 'Meta Ads',
    status: 'scaled',
    budgetDaily: 8500,
    spendToday: 6840,
    impressions: 489200,
    clicks: 14210,
    ctr: 2.9,
    conversions: 612,
    cpa: 11.17,
    targetCpa: 14.50,
    roas: 4.82,
    targetRoas: 3.50,
    attributionShare: 31.4,
    healthScore: 94,
    trend: 'up',
    creativeFatigue: 'low',
    recommendations: ['Increase daily budget cap by 15% before 18:00 UTC', 'Scale high-converting UGC 04 video creative'],
  },
  {
    id: 'cmp-google-intent-02',
    name: 'High-Intent Search Core & Exact Match',
    channel: 'google',
    channelLabel: 'Google Ads',
    status: 'active',
    budgetDaily: 7200,
    spendToday: 5930,
    impressions: 198400,
    clicks: 16890,
    ctr: 8.5,
    conversions: 780,
    cpa: 7.60,
    targetCpa: 9.00,
    roas: 6.14,
    targetRoas: 4.50,
    attributionShare: 38.6,
    healthScore: 98,
    trend: 'up',
    creativeFatigue: 'low',
    recommendations: ['Expand target impression share on competitor queries', 'Enable value-based bidding with first-party LTV signals'],
  },
  {
    id: 'cmp-tiktok-viral-03',
    name: 'Creator Sparks & Spark Ads Retention',
    channel: 'tiktok',
    channelLabel: 'TikTok Ads',
    status: 'throttled',
    budgetDaily: 4000,
    spendToday: 3410,
    impressions: 612000,
    clicks: 9820,
    ctr: 1.6,
    conversions: 184,
    cpa: 18.53,
    targetCpa: 15.00,
    roas: 2.41,
    targetRoas: 3.00,
    attributionShare: 12.8,
    healthScore: 68,
    trend: 'down',
    creativeFatigue: 'high',
    recommendations: ['Rotate 3 exhausted creator videos immediately', 'Shift $800 daily spend to TopView placement'],
  },
  {
    id: 'cmp-ttd-programmatic-04',
    name: 'Premium Connected TV & Video PMP',
    channel: 'programmatic',
    channelLabel: 'The Trade Desk',
    status: 'active',
    budgetDaily: 5500,
    spendToday: 4210,
    impressions: 840000,
    clicks: 4200,
    ctr: 0.5,
    conversions: 245,
    cpa: 17.18,
    targetCpa: 18.00,
    roas: 3.12,
    targetRoas: 2.80,
    attributionShare: 17.2,
    healthScore: 88,
    trend: 'stable',
    creativeFatigue: 'low',
    recommendations: ['Cap frequency to 2.5 per household per 48 hours', 'Whitelabel top 5 performing OTT publishers'],
  },
  {
    id: 'cmp-meta-retarget-05',
    name: 'Dynamic Product Ads (DPA) 14-Day View',
    channel: 'meta',
    channelLabel: 'Meta Ads',
    status: 'active',
    budgetDaily: 3200,
    spendToday: 2680,
    impressions: 112000,
    clicks: 4980,
    ctr: 4.4,
    conversions: 395,
    cpa: 6.78,
    targetCpa: 8.50,
    roas: 7.25,
    targetRoas: 5.00,
    attributionShare: 15.9,
    healthScore: 92,
    trend: 'up',
    creativeFatigue: 'moderate',
    recommendations: ['Test countdown overlay for flash promo inventory', 'Exclude buyers from last 3 days'],
  }
];

export const INITIAL_RULES: ExecutionRule[] = [
  {
    id: 'rule-auto-scale-roas',
    name: 'Algorithmic Scale on High ROAS Surge',
    condition: 'IF ROAS > 4.2x AND Spend > $2,000 in past 4h AND Error Rate < 0.01%',
    action: 'scale_budget',
    actionLabel: 'Increase Daily Budget +20% (Max $12k cap)',
    targetChannel: 'meta',
    status: 'active',
    lastTriggered: '18 minutes ago',
    triggerCount: 42,
    priority: 'p1',
  },
  {
    id: 'rule-killswitch-cpa',
    name: 'Automated Stop-Loss on CPA Spike',
    condition: 'IF Hourly CPA > Target CPA * 1.45 AND Impressions > 10,000',
    action: 'pause_creative',
    actionLabel: 'Throttle Ad Set Spend to Minimum Floor & Alert Ops',
    targetChannel: 'tiktok',
    status: 'active',
    lastTriggered: '2 hours ago',
    triggerCount: 15,
    priority: 'p1',
  },
  {
    id: 'rule-bid-pace-pacing',
    name: 'Smart Bid Pace on Google High Intent',
    condition: 'IF Conversion Rate > 9.5% AND Top of Page Impression Share < 80%',
    action: 'bid_adjust',
    actionLabel: 'Boost Target ROAS Bidding by +8%',
    targetChannel: 'google',
    status: 'active',
    lastTriggered: '35 minutes ago',
    triggerCount: 89,
    priority: 'p2',
  },
  {
    id: 'rule-fatigue-creative',
    name: 'Creative Frequency & Decay Mitigation',
    condition: 'IF Frequency > 3.8 AND CTR decay > 25% over 72h window',
    action: 'dispatch_webhook',
    actionLabel: 'Trigger Dynamic Creative Rotation Webhook to Asset Engine',
    targetChannel: 'all',
    status: 'active',
    lastTriggered: '4 hours ago',
    triggerCount: 23,
    priority: 'p3',
  }
];

export const INITIAL_ALERTS: IntelligenceAlert[] = [
  {
    id: 'alert-1',
    timestamp: '2m ago',
    severity: 'critical',
    title: 'TikTok Ads Creative Saturation Detected',
    message: 'Ad Set #4912 has reached 4.1x frequency; CTR dropped from 2.4% to 1.4% within 6 hours.',
    metric: 'CTR -41.6%',
    automatedAction: 'Throttled hourly spend allocation by 25%',
  },
  {
    id: 'alert-2',
    timestamp: '14m ago',
    severity: 'success',
    title: 'Google High-Intent Surge Triggered Auto-Scale',
    message: 'Exact match conversion velocity +54% vs 7-day average. ROAS reached 6.14x.',
    metric: 'ROAS 6.14x (+1.64 vs Target)',
    automatedAction: 'Budget increased by $1,200',
  },
  {
    id: 'alert-3',
    timestamp: '38m ago',
    severity: 'info',
    title: 'Shapley Attribution Re-balanced Across Channels',
    message: 'Snowflake pipeline processed 1.2M historical session graphs. Upper funnel CTV assisted 18.4% more purchases than legacy first-touch indicated.',
    metric: 'Attribution Lift +18.4%',
    automatedAction: 'Updated real-time attribution matrix',
  },
  {
    id: 'alert-4',
    timestamp: '1h ago',
    severity: 'warning',
    title: 'Meta Ads Webhook Latency Spiked to 110ms',
    message: 'Temporary upstream rate limiting from Graph API. Ingestion engine buffered 84k events in local Kafka topic.',
    metric: 'Queue: 84,200 events',
    automatedAction: 'Auto-flushed buffer to Snowflake',
  }
];

export const INITIAL_LOGS: PipelineEventLog[] = [
  {
    id: 'log-01',
    timestamp: '13:07:22.418',
    pipelineId: 'pipe-google-search',
    pipelineName: 'Google Ads Data Stream',
    type: 'EVENT_INGEST',
    latencyMs: 18,
    payloadSummary: 'Batch 8920 ingested: 14,200 conversion clicks, cost: $3,410.20',
    status: 'success',
  },
  {
    id: 'log-02',
    timestamp: '13:07:22.102',
    pipelineId: 'pipe-meta-ads',
    pipelineName: 'Meta Ads Realtime Stream',
    type: 'ATTRIBUTION_CALCULATED',
    latencyMs: 34,
    payloadSummary: 'Shapley marginal contribution calculated for campaign #cmp-meta-scale-01 (value: 0.314)',
    status: 'success',
  },
  {
    id: 'log-03',
    timestamp: '13:07:21.890',
    pipelineId: 'pipe-tiktok-pixel',
    pipelineName: 'TikTok Events API Stream',
    type: 'RULE_EVALUATED',
    latencyMs: 42,
    payloadSummary: 'Rule #rule-killswitch-cpa evaluated: condition FALSE (hourly CPA within bounds)',
    status: 'success',
  },
  {
    id: 'log-04',
    timestamp: '13:07:21.512',
    pipelineId: 'pipe-dsp-bidstream',
    pipelineName: 'The Trade Desk Bidstream & Win Logs',
    type: 'IDENTITY_RESOLVED',
    latencyMs: 11,
    payloadSummary: 'Resolved 22,400 bid requests to 18,910 household IDs via Unified ID 2.0 (UID2)',
    status: 'success',
  },
  {
    id: 'log-05',
    timestamp: '13:07:20.980',
    pipelineId: 'pipe-snowflake-sink',
    pipelineName: 'Snowflake Enterprise Warehouse Sink',
    type: 'SINK_WRITTEN',
    latencyMs: 62,
    payloadSummary: 'Committed micro-batch #99482 (48,100 records) to RAW_ATTRIBUTION_GRAPH',
    status: 'success',
  }
];

export function getAttributionMetricsByModel(model: AttributionModelType): AttributionChannelMetric[] {
  switch (model) {
    case 'shapley':
      return [
        { channel: 'google', channelLabel: 'Google Ads', attributedConversions: 840, attributedRevenue: 142800, blendedRoas: 5.82, sharePct: 37.8, confidenceInterval: [36.1, 39.5] },
        { channel: 'meta', channelLabel: 'Meta Ads', attributedConversions: 710, attributedRevenue: 118400, blendedRoas: 4.95, sharePct: 32.0, confidenceInterval: [30.4, 33.6] },
        { channel: 'programmatic', channelLabel: 'The Trade Desk', attributedConversions: 390, attributedRevenue: 64200, blendedRoas: 3.42, sharePct: 17.6, confidenceInterval: [15.8, 19.4] },
        { channel: 'tiktok', channelLabel: 'TikTok Ads', attributedConversions: 280, attributedRevenue: 45600, blendedRoas: 2.85, sharePct: 12.6, confidenceInterval: [11.2, 14.0] },
      ];
    case 'markov':
      return [
        { channel: 'google', channelLabel: 'Google Ads', attributedConversions: 890, attributedRevenue: 151300, blendedRoas: 6.16, sharePct: 40.1, confidenceInterval: [38.5, 41.7] },
        { channel: 'meta', channelLabel: 'Meta Ads', attributedConversions: 640, attributedRevenue: 106800, blendedRoas: 4.46, sharePct: 28.8, confidenceInterval: [27.2, 30.4] },
        { channel: 'programmatic', channelLabel: 'The Trade Desk', attributedConversions: 430, attributedRevenue: 70900, blendedRoas: 3.77, sharePct: 19.4, confidenceInterval: [17.9, 20.9] },
        { channel: 'tiktok', channelLabel: 'TikTok Ads', attributedConversions: 260, attributedRevenue: 42000, blendedRoas: 2.62, sharePct: 11.7, confidenceInterval: [10.3, 13.1] },
      ];
    case 'data_driven':
      return [
        { channel: 'google', channelLabel: 'Google Ads', attributedConversions: 810, attributedRevenue: 137700, blendedRoas: 5.61, sharePct: 36.5, confidenceInterval: [35.0, 38.0] },
        { channel: 'meta', channelLabel: 'Meta Ads', attributedConversions: 740, attributedRevenue: 123400, blendedRoas: 5.16, sharePct: 33.3, confidenceInterval: [31.9, 34.7] },
        { channel: 'programmatic', channelLabel: 'The Trade Desk', attributedConversions: 370, attributedRevenue: 60900, blendedRoas: 3.24, sharePct: 16.7, confidenceInterval: [15.1, 18.3] },
        { channel: 'tiktok', channelLabel: 'TikTok Ads', attributedConversions: 300, attributedRevenue: 49000, blendedRoas: 3.06, sharePct: 13.5, confidenceInterval: [12.1, 14.9] },
      ];
    case 'time_decay':
      return [
        { channel: 'google', channelLabel: 'Google Ads', attributedConversions: 960, attributedRevenue: 163200, blendedRoas: 6.65, sharePct: 43.2, confidenceInterval: [41.8, 44.6] },
        { channel: 'meta', channelLabel: 'Meta Ads', attributedConversions: 680, attributedRevenue: 113500, blendedRoas: 4.74, sharePct: 30.6, confidenceInterval: [29.1, 32.1] },
        { channel: 'tiktok', channelLabel: 'TikTok Ads', attributedConversions: 320, attributedRevenue: 52400, blendedRoas: 3.28, sharePct: 14.4, confidenceInterval: [13.0, 15.8] },
        { channel: 'programmatic', channelLabel: 'The Trade Desk', attributedConversions: 260, attributedRevenue: 41900, blendedRoas: 2.23, sharePct: 11.8, confidenceInterval: [10.5, 13.1] },
      ];
    case 'first_touch':
      return [
        { channel: 'programmatic', channelLabel: 'The Trade Desk', attributedConversions: 720, attributedRevenue: 118800, blendedRoas: 6.32, sharePct: 32.4, confidenceInterval: [30.8, 34.0] },
        { channel: 'tiktok', channelLabel: 'TikTok Ads', attributedConversions: 620, attributedRevenue: 101600, blendedRoas: 6.35, sharePct: 27.9, confidenceInterval: [26.3, 29.5] },
        { channel: 'meta', channelLabel: 'Meta Ads', attributedConversions: 510, attributedRevenue: 85100, blendedRoas: 3.56, sharePct: 23.0, confidenceInterval: [21.5, 24.5] },
        { channel: 'google', channelLabel: 'Google Ads', attributedConversions: 370, attributedRevenue: 65500, blendedRoas: 2.67, sharePct: 16.7, confidenceInterval: [15.2, 18.2] },
      ];
  }
}
